### ISSUE TITLE
Find time range selected from portal and use it inside kusto query for APP analytics

### ISSUE THREAD

**Issue by abhijitchaudhari1** [yonileibowitz/kusto.blog#1]
I am trying to find the time range selected from portal and then use it inside the kusto query to calculate the % UP TIME

I have updated the details here: https://stackoverflow.com/questions/55379172/find-the-start-and-end-time-or-time-span-of-the-kusto-query-is-running-on-azur

Thanks for help.

**Comment by yonileibowitz** [comment]
this is a repository of a public blog, and is not a general-purpose forum to promote your Stack Overflow questions.
In the future, please avoid misusing this forum for improper references.
If you have questions/issues identified in the content of the blog - I'd be happy to hear about them.
Otherwise, Stack Overflow is a proper address for technical questions about a specific product you're using.
